# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ASTRA1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QVBoxLayout, QScrollArea, QWidget,QFrame,QScrollBar,QLineEdit,QPushButton
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-130, -180, 1201, 1091))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("black.png"))
        self.label.setScaledContents(True)
        self.label.setIndent(-22)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(770, 760, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(255,255,255);\n"
"color: rgb(69, 94, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 760, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:rgb(255,255,255);\n"
"color: rgb(69, 94, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, -30, 1071, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("2.png"))
        self.label_2.setObjectName("label_2")
        self.TIME = QtWidgets.QGraphicsView(self.centralwidget)
        self.TIME.setGeometry(QtCore.QRect(820, 70, 100, 27))
        self.TIME.setStyleSheet("color:rgb(255, 255, 255);\n"

"font:75 12pt \"MS Shell Dlg 2\";\n"

"border-radius:12px;")
        self.TIME.setObjectName("TIME")
        self.DATE = QtWidgets.QGraphicsView(self.centralwidget)
        self.DATE.setGeometry(QtCore.QRect(700, 70, 100, 27))
        self.DATE.setStyleSheet("color:rgb(255, 255, 255);\n"

"font:75 12pt \"MS Shell Dlg 2\";\n"

"border-radius:12px;")
        self.DATE.setObjectName("DATE")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-170, 100, 1221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 1051, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 800, 1041, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("1.png"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 700, 200, 40))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("\n"
"color:rgb(255, 255, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 501, 561))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("VJl.gif"))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 810, 131, 21))
        self.label_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color:rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(960, 50, 81, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("QWfb.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.CONTENT = QtWidgets.QLabel(self.centralwidget)
        self.CONTENT.setGeometry(QtCore.QRect(540, 140, 461, 601))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.CONTENT.setFont(font)
        self.CONTENT.setMargin(4)
        self.CONTENT.setWordWrap(True)
        
        self.CONTENT.setAutoFillBackground(False)
        self.CONTENT.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 75 7pt \"Sitka Small\";")
        self.CONTENT.setObjectName("CONTENT")
        self.CONTENT.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        # make scrollbar for this vertical
        self.scrollArea = QScrollBar(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(540, 140, 461,
                                                 601))
        self.scrollArea.setMaximumHeight(601)
        self.scrollArea.setOrientation(Qt.Vertical)
        self.scrollArea.setInvertedAppearance(False)
        self.scrollArea.setObjectName('scrollArea')
        self.scrollArea.setEnabled(True)
        self.scrollArea.setVisible(True)
        self.scrollArea.setMinimumWidth(461)
        self.scrollArea.setFixedWidth(461)
        # self.scrollArea.setFrameShape(QFrame.NoFrame)
        # self.scrollArea.setFrameShadow(QFrame.Raised)
        # self.scrollArea.setLineWidth(0)
        self.scrollArea.setPageStep(20)
        self.scrollArea.setSingleStep(1)
        self.scrollArea.setValue(0)
        self.scrollArea.setSliderPosition(0)
        self.scrollArea.setTracking(True)
        self.scrollArea.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setLayoutDirection(Qt.LeftToRight)
        # self.scrollArea.setLocale(QLocale())
        self.scrollArea.setInputMethodHints(Qt.ImhNone)
        self.scrollArea.setAccessibleName("")
        self.scrollArea.setStatusTip("")
        self.scrollArea.setWhatsThis("")
        self.scrollArea.setToolTipDuration(-1)
        self.scrollArea.setFocusPolicy(Qt.ClickFocus)
        self.scrollArea.setTabOrder(self.CONTENT, None)
        # self.scrollArea.setIconSize(QSize(32, 32))
        # self.scrollArea.setAlignment(Qt.AlignCenter)
        # self.scrollArea.setDocumentMode(False)
        # self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        # self.scrollArea.setWidgetResizable(True)
        # self.scrollArea.setEchoMode(QLineEdit.Normal)
        # self.scrollArea.setReadOnly(True)
        # self.scrollArea.setCursorForPosition(QPointF(), Qt.IBeamCursor)
        # self.scrollArea.setSelectionStart(0)
        # self.scrollArea.setSelectionEnd(0)
        # self.scrollArea.setPlaceholderText("")
        # self.scrollArea.setClearButtonEnabled(False)
        # self.scrollArea.setMask(QRegion())
        # self.scrollArea.setAccelerated()
        self.scrollArea.setAutoFillBackground(False)
        # self.scrollArea.setStyleSheet("#scrollArea { background-color: rgb(255, 255,
        #                               255); }")
        # # self.scrollArea.setFontWeight(50)
        # self.scrollArea.setMouseTracking(False)
        # self.scrollArea.setTextInteractionFlags(Qt.LinksBypassUrlCheck |
        #                                         Qt.TextBrowserInteraction |
        #                                         Qt.TextSelectableByKeyboard |
        #                                         Qt.TextSelectableByMouse)
        # self.scrollArea.setOpenExternalLinks(True)
        # self.scrollArea.setUndoRedoEnabled(False)
        # self.scrollArea.setMaxLength(32768)
        # # self.scrollArea.setCorrectionMode(QAbstractSpinBox.CorrectOnKeystroke)
        # self.scrollArea.setPrefix("")
        # self.scrollArea.setSuffix("")
        # self.scrollArea.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.scrollArea.setMinimum(0)
        self.scrollArea.setMaximum(999999999)
        self.scrollArea.setValue(0)
        # self.scrollArea.setWrapping(False)
        # self.scrollArea.setFrameShape(QFrame.NoFrame)
        # self.scrollArea.setLineWidth(1)
        # self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setObjectName("scrollArea")







        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.TIME.raise_()
        self.DATE.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.CONTENT.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.pushButton_2.setText(_translate("MainWindow", "EXIT"))
        self.label_5.setText(_translate("MainWindow", "ASTRA"))
        self.label_4.setText(_translate("MainWindow", "kushal1o1©️"))
        self.CONTENT.setText(_translate("MainWindow", "                                                 Astra Model 1.1version\n\n                                                     owner:kushal1o1😎\n\n                                              📧:kushalbaral1o1@gmail.com\n\n                                                 Click Run to Continue \n                                              -------------------------------\n              🤖"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
